import { IMAGES, SVGICON } from "../../constant/theme";

export const CompanyData = [
  {
    id: "1001",
    image: IMAGES.contact1,
    parent: "business1@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company1@example.com",
    zipCode: "125656",
    status: "Active",
    title: "Ricky Antony",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1002",
    image: IMAGES.contact2,
    parent: "business2@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company2@example.com",
    zipCode: "234346",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1003",
    image: IMAGES.contact3,
    parent: "business3@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company3@example.com",
    zipCode: "343226",
    status: "Active",
    title: "Ricky M",
    email: "pqr@gmail.com",
    city: "France",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1004",
    image: IMAGES.contact1,
    parent: "business4@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company4@example.com",
    zipCode: "145456",
    status: "Active",
    title: "Elijah James",
    email: "stuy@gmail.com",
    city: "Dubai",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1005",
    image: IMAGES.contact2,
    parent: "business5@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company5@example.com",
    zipCode: "123126",
    status: "Inactive",
    title: "Honey Risher",
    email: "xyz@gmail.com",
    city: "USA",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1006",
    image: IMAGES.contact2,
    parent: "business1@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company6@example.com",
    zipCode: "897456",
    status: "Active",
    title: "Honey Risher",
    email: "xyz@gmail.com",
    city: "USA",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1007",
    image: IMAGES.contact2,
    parent: "business2@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company7@example.com",
    zipCode: "178636",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1008",
    image: IMAGES.contact3,
    parent: "business3@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company8@example.com",
    zipCode: "678936",
    status: "Active",
    title: "Ricky M",
    email: "pqr@gmail.com",
    city: "France",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1009",
    image: IMAGES.contact1,
    parent: "business4@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company9@example.com",
    zipCode: "942546",
    status: "Inactive",
    title: "Abhinav",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1010",
    image: IMAGES.contact1,
    parent: "business5@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company10@example.com",
    zipCode: "685676",
    status: "Active",
    title: "Elijah James",
    email: "stuy@gmail.com",
    city: "Dubai",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1011",
    image: IMAGES.contact2,
    parent: "business1@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company11@example.com",
    zipCode: "907334",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1012",
    image: IMAGES.contact1,
    parent: "business2@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company12@example.com",
    zipCode: "934234",
    status: "Active",
    title: "Kartik",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1013",
    image: IMAGES.contact1,
    parent: "business3@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company13@example.com",
    zipCode: "134523",
    status: "Active",
    title: "Sharad",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1014",
    image: IMAGES.contact1,
    parent: "business4@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company14@example.com",
    zipCode: "904563",
    status: "Active",
    title: "Arpit",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1015",
    image: IMAGES.contact1,
    parent: "business5@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company15@example.com",
    zipCode: "178455",
    status: "Active",
    title: "Krishna",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1016",
    image: IMAGES.contact2,
    parent: "business1@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company16@example.com",
    zipCode: "452343",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1017",
    image: IMAGES.contact1,
    parent: "business2@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company17@example.com",
    zipCode: "463453",
    status: "Active",
    title: "Piyush",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1018",
    image: IMAGES.contact1,
    parent: "business3@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company18@example.com",
    zipCode: "123454",
    status: "Inactive",
    title: "Milan",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1019",
    image: IMAGES.contact1,
    parent: "business4@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company19@example.com",
    zipCode: "908566",
    status: "Active",
    title: "Gagan sir",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1020",
    image: IMAGES.contact1,
    parent: "business5@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company20@example.com",
    zipCode: "646454",
    status: "Inactive",
    title: "Akshay",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
];

export const BusinessData = [
  {
    id: "1001",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business1@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "125656",
    status: "Active",
    title: "Ricky Antony",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1002",
    image: IMAGES.contact2,
    parent: "admin@example.com",
    businessUser: "business2@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "234346",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1003",
    image: IMAGES.contact3,
    parent: "admin@example.com",
    businessUser: "business3@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "343226",
    status: "Active",
    title: "Ricky M",
    email: "pqr@gmail.com",
    city: "France",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1004",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business4@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "145456",
    status: "Active",
    title: "Elijah James",
    email: "stuy@gmail.com",
    city: "Dubai",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1005",
    image: IMAGES.contact2,
    parent: "admin@example.com",
    businessUser: "business5@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "123126",
    status: "Inactive",
    title: "Honey Risher",
    email: "xyz@gmail.com",
    city: "USA",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1006",
    image: IMAGES.contact2,
    parent: "admin@example.com",
    businessUser: "business6@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "897456",
    status: "Active",
    title: "Honey Risher",
    email: "xyz@gmail.com",
    city: "USA",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1007",
    image: IMAGES.contact2,
    parent: "admin@example.com",
    businessUser: "business7@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "178636",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1008",
    image: IMAGES.contact3,
    parent: "admin@example.com",
    businessUser: "business7@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "678936",
    status: "Active",
    title: "Ricky M",
    email: "pqr@gmail.com",
    city: "France",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1009",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business8@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "942546",
    status: "Inactive",
    title: "Abhinav",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1010",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business9@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "685676",
    status: "Active",
    title: "Elijah James",
    email: "stuy@gmail.com",
    city: "Dubai",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1011",
    image: IMAGES.contact2,
    parent: "admin@example.com",
    businessUser: "business10@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "907334",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1012",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business11@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "934234",
    status: "Active",
    title: "Kartik",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1013",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business12@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "134523",
    status: "Active",
    title: "Sharad",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1014",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business13@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "904563",
    status: "Active",
    title: "Arpit",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1015",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business14@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "178455",
    status: "Active",
    title: "Krishna",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1016",
    image: IMAGES.contact2,
    parent: "admin@example.com",
    businessUser: "business15@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "452343",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1017",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business16@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "463453",
    status: "Active",
    title: "Piyush",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1018",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business17@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "123454",
    status: "Inactive",
    title: "Milan",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1019",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business18@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "908566",
    status: "Active",
    title: "Gagan sir",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1020",
    image: IMAGES.contact1,
    parent: "admin@example.com",
    businessUser: "business19@example.com",
    mobileNumber: "+91 123 456 7890",
    zipCode: "646454",
    status: "Inactive",
    title: "Akshay",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
];

export const UserData = [
  {
    id: "1001",
    age: 32,
    image: IMAGES.contact1,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    userName: "Ricky Antony",
    experience: 5,
    gender: "Female",
    country: "India",
    branches: 4,
  },
  {
    id: "1002",
    age: 29,
    image: IMAGES.contact2,
    mobileNumber: "+91 123 456 7890",
    status: "Inactive",
    userName: "Ankites Risher",
    experience: 7,
    gender: "Male",
    country: "Brazil",
    branches: 4,
  },
  {
    id: "1003",
    age: 41,
    image: IMAGES.contact3,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    userName: "Ricky M",
    experience: 3,
    gender: "Male",
    country: "France",
    branches: 4,
  },
  {
    id: "1004",
    age: 31,
    image: IMAGES.contact1,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    userName: "Elijah James",
    experience: 5,
    gender: "Female",
    country: "Dubai",
    branches: 4,
  },
  {
    id: "1005",
    age: 32,
    image: IMAGES.contact2,
    mobileNumber: "+91 123 456 7890",
    status: "Inactive",
    userName: "Honey Risher",
    experience: 5,
    gender: "Male",
    country: "USA",
    branches: 4,
  },
  {
    id: "1006",
    age: 42,
    image: IMAGES.contact2,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    userName: "Honey Risher",
    experience: 9,
    gender: "Male",
    country: "USA",
    branches: 4,
  },
  {
    id: "1007",
    age: 32,
    image: IMAGES.contact2,
    mobileNumber: "+91 123 456 7890",
    status: "Inactive",
    userName: "Ankites Risher",
    experience: 5,
    gender: "Male",
    country: "Brazil",
    branches: 4,
  },
  {
    id: "1008",
    age: 34,
    image: IMAGES.contact3,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    userName: "Ricky M",
    experience: 4,
    gender: "Male",
    country: "France",
    branches: 4,
  },
  {
    id: "1009",
    age: 32,
    image: IMAGES.contact1,
    mobileNumber: "+91 123 456 7890",
    status: "Inactive",
    userName: "Ricky Antony",
    experience: 5,
    gender: "Female",
    country: "India",
    branches: 4,
  },
  {
    id: "1010",
    age: 29,
    image: IMAGES.contact1,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    userName: "Elijah James",
    experience: 8,
    gender: "Female",
    country: "Dubai",
    branches: 4,
  },
  {
    id: "1011",
    age: 32,
    image: IMAGES.contact2,
    mobileNumber: "+91 123 456 7890",
    status: "Inactive",
    userName: "Ankites Risher",
    experience: 3,
    gender: "Male",
    country: "Brazil",
    branches: 4,
  },
  {
    id: "1012",
    age: 32,
    image: IMAGES.contact1,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    userName: "Ricky Antony",
    experience: 5,
    gender: "Female",
    country: "India",
    branches: 4,
  },
];
export const TechnicianData = [
  {
    id: "1001",
    image: IMAGES.contact1,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    firstName: "Ricky Antony",
    email: "ra@gmail.com",
    country: "India",
  },
  {
    id: "1002",
    image: IMAGES.contact2,
    mobileNumber: "+91 123 456 7890",
    status: "Inactive",
    firstName: "Ankites Risher",
    email: "abc@gmail.com",
    country: "Brazil",
  },
  {
    id: "1003",
    image: IMAGES.contact3,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    firstName: "Ricky M",
    email: "pqr@gmail.com",
    country: "France",
  },
  {
    id: "1004",
    image: IMAGES.contact1,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    firstName: "Elijah James",
    email: "stuy@gmail.com",
    country: "Dubai",
  },
  {
    id: "1005",
    image: IMAGES.contact2,
    mobileNumber: "+91 123 456 7890",
    status: "Inactive",
    firstName: "Honey Risher",
    email: "xyz@gmail.com",
    country: "USA",
  },
  {
    id: "1006",
    image: IMAGES.contact2,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    firstName: "Honey Risher",
    email: "xyz@gmail.com",
    country: "USA",
  },
  {
    id: "1007",
    image: IMAGES.contact2,
    mobileNumber: "+91 123 456 7890",
    status: "Inactive",
    firstName: "Ankites Risher",
    email: "abc@gmail.com",
    country: "Brazil",
  },
  {
    id: "1008",
    image: IMAGES.contact3,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    firstName: "Ricky M",
    email: "pqr@gmail.com",
    country: "France",
  },
  {
    id: "1009",
    image: IMAGES.contact1,
    mobileNumber: "+91 123 456 7890",
    status: "Inactive",
    firstName: "Ricky Antony",
    email: "ra@gmail.com",
    country: "India",
  },
  {
    id: "1010",
    image: IMAGES.contact1,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    firstName: "Elijah James",
    email: "stuy@gmail.com",
    country: "Dubai",
  },
  {
    id: "1011",
    image: IMAGES.contact2,
    mobileNumber: "+91 123 456 7890",
    status: "Inactive",
    firstName: "Ankites Risher",
    email: "abc@gmail.com",
    country: "Brazil",
  },
  {
    id: "1012",
    image: IMAGES.contact1,
    mobileNumber: "+91 123 456 7890",
    status: "Active",
    firstName: "Ricky Antony",
    email: "ra@gmail.com",
    country: "India",
  },
];
export const DriverData = [
  {
    id: "1001",
    branch: "company1@example.com",
    firstName: "Rahul",
    lastName: "Verma",
    status: true,
    age: 34,
    drivingExperienceSince: 2015,
    contactNumber1: "+91 123 456 7890",
    createdDate: "2024-02-23",
    city: "Mumbai",
    parentCompany: "Company4",
    parentBusiness: "Business Group1",
  },
  {
    id: "1002",
    branch: "company1@example.com",
    firstName: "John",
    lastName: "Doe",
    status: false,
    age: 29,
    drivingExperienceSince: 2015,
    contactNumber1: "+1 234 567 8901",
    createdDate: "2024-02-21",
    city: "New York",
    parentCompany: "Company4",
    parentBusiness: "Business Group2",
  },

  {
    id: "2001",
    branch: "company2@example.com",
    firstName: "David",
    lastName: "Smith",
    status: true,
    age: 30,
    drivingExperienceSince: 2015,
    contactNumber1: "+1 987 654 3210",
    createdDate: "2024-03-10",
    city: "Los Angeles",
    parentCompany: "Company3",
    parentBusiness: "Business Group3",
  },

  {
    id: "2002",
    branch: "company2@example.com",
    firstName: "Emma",
    lastName: "Johnson",
    status: false,
    age: 27,
    drivingExperienceSince: 2015,
    contactNumber1: "+44 987 654 3210",
    createdDate: "2024-01-24",
    city: "London",
    parentCompany: "Company3",
    parentBusiness: "Business Group4",
  },

  {
    id: "3001",
    branch: "company3@example.com",
    firstName: "Liam",
    lastName: "Martin",
    status: true,
    age: 31,
    drivingExperienceSince: 2015,
    contactNumber1: "+1 876 543 2109",
    createdDate: "2024-02-11",
    city: "Sydney",
    parentCompany: "Company2",
    parentBusiness: "Business Group5",
  },
  {
    id: "3002",
    branch: "company3@example.com",
    firstName: "Ava",
    lastName: "Brown",
    status: false,
    age: 28,
    drivingExperienceSince: 2015,
    contactNumber1: "+44 876 543 2109",
    createdDate: "2024-02-15",
    city: "Manchester",
    parentCompany: "Company2",
    parentBusiness: "Business Group1",
  },
  {
    id: "4001",
    branch: "company4@example.com",
    firstName: "Emma",
    lastName: "Garcia",
    status: true,
    age: 28,
    drivingExperienceSince: 2015,
    contactNumber1: "+1 765 432 1098",
    createdDate: "2024-02-21",
    city: "Chicago",
    parentCompany: "Company2",
    parentBusiness: "Business Group1",
  },
  {
    id: "4002",
    branch: "company4@example.com",
    firstName: "Olivia",
    lastName: "Brown",
    status: false,
    age: 27,
    drivingExperienceSince: 2015,
    contactNumber1: "+44 765 432 1098",
    createdDate: "2024-02-11",
    city: "Birmingham",
    parentCompany: "Company1",
    parentBusiness: "Business Group2",
  },

  {
    id: "5001",
    branch: "company5@example.com",
    firstName: "Noah",
    lastName: "Martinez",
    status: true,
    age: 32,
    drivingExperienceSince: 2015,
    contactNumber1: "+1 654 321 0987",
    createdDate: "2024-03-12",
    city: "Houston",
    parentCompany: "Company1",
    parentBusiness: "Business Group3",
  },
  {
    id: "5002",
    branch: "company5@example.com",
    firstName: "Sophia",
    lastName: "Jones",
    status: false,
    age: 29,
    drivingExperienceSince: 2015,
    contactNumber1: "+44 654 321 0987",
    createdDate: "2024-02-11",
    city: "Manchester",
    parentCompany: "Company1",
    parentBusiness: "Business Group3",
  },
];

export const FuelData = [
  {
    id: "1001",
    createdDate: "2024-02-23",
    parentCompany: "Company4",
    parentBusiness: "Business Group1",
    vehicleName: "Vehicle A",
    fuelConsumed: 50, // in liters
    mileage: 12, // in kilometers per liter
    drain: false,
    duration: 2, // in hours
    maxStoppage: 30, // in minutes
    distance: 120, // in kilometers
  },
  {
    id: "1002",
    createdDate: "2024-02-21",
    parentCompany: "Company4",
    parentBusiness: "Business Group2",
    vehicleName: "Vehicle B",
    fuelConsumed: 60,
    mileage: 15,
    drain: true,
    duration: 2.5,
    maxStoppage: 45,
    distance: 150,
  },
  {
    id: "2001",
    createdDate: "2024-03-10",
    parentCompany: "Company3",
    parentBusiness: "Business Group3",
    vehicleName: "Vehicle C",
    fuelConsumed: 70,
    mileage: 14,
    drain: false,
    duration: 3,
    maxStoppage: 60,
    distance: 200,
  },
  {
    id: "2002",
    createdDate: "2024-01-24",
    parentCompany: "Company3",
    parentBusiness: "Business Group4",
    vehicleName: "Vehicle D",
    fuelConsumed: 55,
    mileage: 11,
    drain: true,
    duration: 2.5,
    maxStoppage: 45,
    distance: 150,
  },
  {
    id: "3001",
    createdDate: "2024-02-11",
    parentCompany: "Company2",
    parentBusiness: "Business Group5",
    vehicleName: "Vehicle E",
    fuelConsumed: 65,
    mileage: 13,
    drain: false,
    duration: 3,
    maxStoppage: 60,
    distance: 195,
  },
  {
    id: "3002",
    createdDate: "2024-02-15",
    parentCompany: "Company2",
    parentBusiness: "Business Group1",
    vehicleName: "Vehicle F",
    fuelConsumed: 75,
    mileage: 15,
    drain: true,
    duration: 3.5,
    maxStoppage: 45,
    distance: 225,
  },
  {
    id: "4001",
    createdDate: "2024-02-21",
    parentCompany: "Company2",
    parentBusiness: "Business Group1",
    vehicleName: "Vehicle G",
    fuelConsumed: 70,
    mileage: 14,
    drain: false,
    duration: 3,
    maxStoppage: 60,
    distance: 210,
  },
  {
    id: "4002",
    createdDate: "2024-02-11",
    parentCompany: "Company1",
    parentBusiness: "Business Group2",
    vehicleName: "Vehicle H",
    fuelConsumed: 60,
    mileage: 12,
    drain: true,
    duration: 2.5,
    maxStoppage: 45,
    distance: 180,
  },
  {
    id: "5001",
    createdDate: "2024-03-12",
    parentCompany: "Company1",
    parentBusiness: "Business Group3",
    vehicleName: "Vehicle I",
    fuelConsumed: 80,
    mileage: 16,
    drain: false,
    duration: 4,
    maxStoppage: 90,
    distance: 240,
  },
  {
    id: "5002",
    createdDate: "2024-02-11",
    parentCompany: "Company1",
    parentBusiness: "Business Group3",
    vehicleName: "Vehicle J",
    fuelConsumed: 55,
    mileage: 11,
    drain: true,
    duration: 2.5,
    maxStoppage: 45,
    distance: 165,
  },
];

export const tripData = [
  {
    id: "1001",
    firstName: "Rahul",
    lastName: "Verma",
    parentCompany: "Company4",
    parentBusiness: "Business Group1",
    activeTrips: 3,
    plannedTrips: 15,
    completedTrips: 8,
    totalTrips: 26,
    totalDuration: 320,
    totalDistance: 180,
    createdDate: "2024-02-11",
  },
  {
    id: "1002",
    firstName: "John",
    parentCompany: "Company4",
    parentBusiness: "Business Group2",
    activeTrips: 6,
    plannedTrips: 18,
    completedTrips: 12,
    totalTrips: 36,
    totalDuration: 420,
    totalDistance: 250,
    createdDate: "2024-02-11",
  },
  {
    id: "2001",
    firstName: "David",
    lastName: "Smith",
    parentCompany: "Company3",
    parentBusiness: "Business Group3",
    activeTrips: 4,
    plannedTrips: 12,
    completedTrips: 10,
    totalTrips: 26,
    totalDuration: 380,
    totalDistance: 220,
    createdDate: "2023-12-11",
  },
  {
    id: "2002",
    firstName: "Emma",
    lastName: "Johnson",
    parentCompany: "Company3",
    parentBusiness: "Business Group4",
    activeTrips: 2,
    plannedTrips: 10,
    completedTrips: 6,
    totalTrips: 18,
    totalDuration: 280,
    totalDistance: 150,
    createdDate: "2024-01-01",
  },
  {
    id: "3001",
    firstName: "Liam",
    lastName: "Martin",
    parentCompany: "Company2",
    parentBusiness: "Business Group5",
    activeTrips: 5,
    plannedTrips: 20,
    completedTrips: 15,
    totalTrips: 40,
    totalDuration: 480,
    totalDistance: 300,
    createdDate: "2024-01-05",
  },
  {
    id: "3002",
    firstName: "Ava",
    lastName: "Brown",
    parentCompany: "Company2",
    parentBusiness: "Business Group1",
    activeTrips: 7,
    plannedTrips: 22,
    completedTrips: 18,
    totalTrips: 47,
    totalDuration: 560,
    totalDistance: 320,
    createdDate: "2024-02-24",
  },
  {
    id: "4001",
    firstName: "Emma",
    lastName: "Garcia",
    parentCompany: "Company2",
    parentBusiness: "Business Group1",
    activeTrips: 4,
    plannedTrips: 16,
    completedTrips: 12,
    totalTrips: 32,
    totalDuration: 420,
    totalDistance: 280,
    createdDate: "2024-1-26",
  },
  {
    id: "4002",
    firstName: "Olivia",
    lastName: "Brown",
    parentCompany: "Company1",
    parentBusiness: "Business Group2",
    activeTrips: 3,
    plannedTrips: 14,
    completedTrips: 10,
    totalTrips: 27,
    totalDuration: 360,
    totalDistance: 200,
    createdDate: "2024-01-21",
  },
  {
    id: "5001",
    firstName: "Noah",
    lastName: "Martinez",
    parentCompany: "Company1",
    parentBusiness: "Business Group3",
    activeTrips: 6,
    plannedTrips: 18,
    completedTrips: 14,
    totalTrips: 38,
    totalDuration: 460,
    totalDistance: 260,
    createdDate: "2024-01-31",
  },
  {
    id: "5002",
    firstName: "Sophia",
    lastName: "Jones",
    parentCompany: "Company1",
    parentBusiness: "Business Group3",
    activeTrips: 8,
    plannedTrips: 20,
    completedTrips: 16,
    totalTrips: 44,
    totalDuration: 520,
    totalDistance: 300,
    createdDate: "2024-01-08",
  },
];

export const SubCompanyData = [
  {
    id: "1001",
    image: IMAGES.contact1,
    businessUser: "business1@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company1@example.com",
    shortName: "branch1@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "125656",
    status: "Active",
    title: "Ricky Antony",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1002",
    image: IMAGES.contact2,
    businessUser: "business2@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company2@example.com",
    shortName: "branch2@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "234346",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1003",
    image: IMAGES.contact3,
    businessUser: "business3@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company3@example.com",
    shortName: "branch3@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "343226",
    status: "Active",
    title: "Ricky M",
    email: "pqr@gmail.com",
    city: "France",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1004",
    image: IMAGES.contact1,
    businessUser: "business4@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company4@example.com",
    shortName: "branch4@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "145456",
    status: "Active",
    title: "Elijah James",
    email: "stuy@gmail.com",
    city: "Dubai",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1005",
    image: IMAGES.contact2,
    businessUser: "business5@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company5@example.com",
    shortName: "branch5@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "123126",
    status: "Inactive",
    title: "Honey Risher",
    email: "xyz@gmail.com",
    city: "USA",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1006",
    image: IMAGES.contact2,
    businessUser: "business1@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company1@example.com",
    shortName: "branch6@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "897456",
    status: "Active",
    title: "Honey Risher",
    email: "xyz@gmail.com",
    city: "USA",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1007",
    image: IMAGES.contact2,
    businessUser: "business2@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company2@example.com",
    shortName: "branch7@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "178636",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1008",
    image: IMAGES.contact3,
    businessUser: "business3@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company3@example.com",
    shortName: "branch8@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "678936",
    status: "Active",
    title: "Ricky M",
    email: "pqr@gmail.com",
    city: "France",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1009",
    image: IMAGES.contact1,
    businessUser: "business4@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company4@example.com",
    shortName: "branch9@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "942546",
    status: "Inactive",
    title: "Abhinav",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1010",
    image: IMAGES.contact1,
    businessUser: "business5@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company5@example.com",
    shortName: "branch10@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "685676",
    status: "Active",
    title: "Elijah James",
    email: "stuy@gmail.com",
    city: "Dubai",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1011",
    image: IMAGES.contact2,
    businessUser: "business1@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company1@example.com",
    shortName: "branch11@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "907334",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1012",
    image: IMAGES.contact1,
    businessUser: "business2@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company2@example.com",
    shortName: "branch12@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "934234",
    status: "Active",
    title: "Kartik",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1013",
    image: IMAGES.contact1,
    businessUser: "business3@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company3@example.com",
    shortName: "branch13@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "134523",
    status: "Active",
    title: "Sharad",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1014",
    image: IMAGES.contact1,
    businessUser: "business4@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company4@example.com",
    shortName: "branch14@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "904563",
    status: "Active",
    title: "Arpit",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1015",
    image: IMAGES.contact1,
    businessUser: "business5@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company5@example.com",
    shortName: "branch15@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "178455",
    status: "Active",
    title: "Krishna",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1016",
    image: IMAGES.contact2,
    businessUser: "business1@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company1@example.com",
    shortName: "branch12@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "452343",
    status: "Inactive",
    title: "Ankites Risher",
    email: "abc@gmail.com",
    city: "Brazil",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1017",
    image: IMAGES.contact1,
    businessUser: "business2@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company2@example.com",
    shortName: "branch17@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "463453",
    status: "Active",
    title: "Piyush",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1018",
    image: IMAGES.contact1,
    businessUser: "business3@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company3@example.com",
    shortName: "branch18@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "123454",
    status: "Inactive",
    title: "Milan",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1019",
    image: IMAGES.contact1,
    businessUser: "business4@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company4@example.com",
    shortName: "branch19@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "908566",
    status: "Active",
    title: "Gagan sir",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
  {
    id: "1020",
    image: IMAGES.contact1,
    businessUser: "business5@example.com",
    mobileNumber: "+91 123 456 7890",
    company: "company5@example.com",
    shortName: "branch20@example.com",
    parentbranch: "branch1@example.com",
    zipCode: "646454",
    status: "Inactive",
    title: "Akshay",
    email: "ra@gmail.com",
    city: "India",
    usergroup: "West Minister Company",
    CompanyGroups: 5,
  },
];

export const VehicleData = [
  {
    id: "1001",
    company: "company1@example.com",
    plateNumber: "ABC123",
    vehicleName: "Toyota Camry",
    simNumber: "123456789012",
    IMEINumber: "987654321012",
    registrationNumber: "566456123",
    branch: "branch1@example.com",
    DVIRTemplate: "CAR-567",
  },
  {
    id: "1002",
    company: "company2@example.com",
    plateNumber: "XYZ456",
    vehicleName: "Honda Civic",
    simNumber: "234567890123",
    IMEINumber: "876543210123",
    registrationNumber: "566456456",
    branch: "branch2@example.com",
    DVIRTemplate: "CAR-457",
  },
  {
    id: "1003",
    company: "company3@example.com",
    plateNumber: "DEF789",
    vehicleName: "Ford F-150",
    simNumber: "345678901234",
    IMEINumber: "765432109876",
    registrationNumber: "566456789",
    branch: "branch3@example.com",
    DVIRTemplate: "CAR-545",
  },
  {
    id: "1004",
    company: "company4@example.com",
    plateNumber: "GHI012",
    vehicleName: "Tesla Model 3",
    simNumber: "456789012345",
    IMEINumber: "654321098765",
    registrationNumber: "566456012",
    branch: "branch4@example.com",
    DVIRTemplate: "CAR-467",
  },
  {
    id: "1005",
    company: "company5@example.com",
    plateNumber: "JKL345",
    vehicleName: "Chevrolet Silverado",
    simNumber: "567890123456",
    IMEINumber: "543210987654",
    registrationNumber: "566456345",
    branch: "branch5@example.com",
    DVIRTemplate: "CAR-345",
  },
  {
    id: "1006",
    company: "company1@example.com",
    plateNumber: "MNO678",
    vehicleName: "BMW X5",
    simNumber: "678901234567",
    IMEINumber: "432109876543",
    registrationNumber: "566456678",
    branch: "branch1@example.com",
    DVIRTemplate: "CAGR-567",
  },
  {
    id: "1007",
    company: "company2@example.com",
    plateNumber: "PQR901",
    vehicleName: "Mercedes-Benz E-Class",
    simNumber: "789012345678",
    IMEINumber: "321098765432",
    registrationNumber: "566456901",
    branch: "branch2@example.com",
    DVIRTemplate: "CAQR-567",
  },
  {
    id: "1008",
    company: "company3@example.com",
    plateNumber: "STU234",
    vehicleName: "Audi Q5",
    simNumber: "890123456789",
    IMEINumber: "210987654321",
    registrationNumber: "566456234",
    branch: "branch3@example.com",
    DVIRTemplate: "CASR-567",
  },
  {
    id: "1009",
    company: "company4@example.com",
    plateNumber: "VWX567",
    vehicleName: "Volkswagen Golf",
    simNumber: "345678901234",
    IMEINumber: "109876543210",
    registrationNumber: "566456567",
    branch: "branch4@example.com",
    DVIRTemplate: "RCAR-56347",
  },
  {
    id: "1010",
    company: "company5@example.com",
    plateNumber: "YZA890",
    vehicleName: "Hyundai Elantra",
    simNumber: "012345678901",
    IMEINumber: "876543210123",
    registrationNumber: "566456890",
    branch: "branch5@example.com",
    DVIRTemplate: "CART-8567",
  },
  {
    id: "1011",
    company: "company1@example.com",
    plateNumber: "BCD123",
    vehicleName: "Subaru Outback",
    simNumber: "123456789012",
    IMEINumber: "654321098765",
    registrationNumber: "566456123",
    branch: "branch1@example.com",
    DVIRTemplate: "ZCAR-56347",
  },
  {
    id: "1012",
    company: "company2@example.com",
    plateNumber: "EFG456",
    vehicleName: "Nissan Altima",
    simNumber: "890123456789",
    IMEINumber: "876543210987",
    registrationNumber: "566456456",
    branch: "branch2@example.com",
    DVIRTemplate: "KCAR-45667",
  },
  {
    id: "1013",
    company: "company3@example.com",
    plateNumber: "BCD123",
    vehicleName: "BMW X5",
    simNumber: "345678901234",
    IMEINumber: "654321098765",
    registrationNumber: "56645612453",
    branch: "branch3@example.com",
    DVIRTemplate: "ZCAR-56347",
  },
  {
    id: "1014",
    company: "company4@example.com",
    plateNumber: "EFG456",
    vehicleName: "Tesla Model 3",
    simNumber: "234567890123",
    IMEINumber: "876543210123",
    registrationNumber: "56645645456",
    branch: "branch4@example.com",
    DVIRTemplate: "KCAR-6756",
  },
  {
    id: "1015",
    company: "company5@example.com",
    plateNumber: "EFG456",
    vehicleName: "Mercedes-Benz E-Class",
    simNumber: "890123456789",
    IMEINumber: "876543210987",
    registrationNumber: "566456456",
    branch: "branch5@example.com",
    DVIRTemplate: "KCAR-456467",
  },
  {
    id: "1016",
    company: "company1@example.com",
    plateNumber: "MNO678",
    vehicleName: "BMW X5",
    simNumber: "678901234567",
    IMEINumber: "432109876543",
    registrationNumber: "566456678",
    branch: "branch1@example.com",
    DVIRTemplate: "CAGR-567",
  },
  {
    id: "1017",
    company: "company2@example.com",
    plateNumber: "PQR901",
    vehicleName: "Mercedes-Benz E-Class",
    simNumber: "789012345678",
    IMEINumber: "321098765432",
    registrationNumber: "566456901",
    branch: "branch2@example.com",
    DVIRTemplate: "CAQR-567",
  },
  {
    id: "1018",
    company: "company3@example.com",
    plateNumber: "STU234",
    vehicleName: "Audi Q5",
    simNumber: "890123456789",
    IMEINumber: "210987654321",
    registrationNumber: "566456234",
    branch: "branch3@example.com",
    DVIRTemplate: "CASR-567",
  },
  {
    id: "1019",
    company: "company4@example.com",
    plateNumber: "VWX567",
    vehicleName: "Volkswagen Golf",
    simNumber: "345678901234",
    IMEINumber: "109876543210",
    registrationNumber: "566456567",
    branch: "branch4@example.com",
    DVIRTemplate: "RCAR-56347",
  },
  {
    id: "1020",
    company: "company3@example.com",
    plateNumber: "YZA890",
    vehicleName: "Hyundai Elantra",
    simNumber: "012345678901",
    IMEINumber: "876543210123",
    registrationNumber: "566456890",
    branch: "branch3@example.com",
    DVIRTemplate: "CART-8567",
  },
  {
    id: "1021",
    company: "company1@example.com",
    plateNumber: "ABC123",
    vehicleName: "Toyota Camry",
    simNumber: "123456789012",
    IMEINumber: "987654321012",
    registrationNumber: "566456123",
    branch: "branch1@example.com",
    DVIRTemplate: "CAR-567",
  },
  {
    id: "1022",
    company: "company2@example.com",
    plateNumber: "XYZ456",
    vehicleName: "Honda Civic",
    simNumber: "234567890123",
    IMEINumber: "876543210123",
    registrationNumber: "566456456",
    branch: "branch2@example.com",
    DVIRTemplate: "CAR-457",
  },
  {
    id: "1023",
    company: "company4@example.com",
    plateNumber: "DEF789",
    vehicleName: "Ford F-150",
    simNumber: "345678901234",
    IMEINumber: "765432109876",
    registrationNumber: "566456789",
    branch: "branch4@example.com",
    DVIRTemplate: "CAR-545",
  },
  {
    id: "1024",
    company: "company5@example.com",
    plateNumber: "GHI012",
    vehicleName: "Tesla Model 3",
    simNumber: "456789012345",
    IMEINumber: "654321098765",
    registrationNumber: "566456012",
    branch: "branch5@example.com",
    DVIRTemplate: "CAR-467",
  },
  {
    id: "1025",
    company: "company5@example.com",
    plateNumber: "JKL345",
    vehicleName: "Chevrolet Silverado",
    simNumber: "567890123456",
    IMEINumber: "543210987654",
    registrationNumber: "566456345",
    branch: "branch5@example.com",
    DVIRTemplate: "CAR-345",
  },
];

export const ExpenseData = [
  {
    id: 1001,
    vehicle: "Toyota Camry",
    expenseDate: "2024-02-23",
    amount: 500,
    description: "Fuel refill",
  },
  {
    id: 1002,
    vehicle: "Honda Civic",
    expenseDate: "2024-02-22",
    amount: 300,
    description: "Oil change",
  },
  {
    id: 1003,
    vehicle: "Ford Mustang",
    expenseDate: "2024-02-21",
    amount: 800,
    description: "Tire replacement",
  },
  {
    id: 1004,
    vehicle: "Chevrolet Silverado",
    expenseDate: "2024-02-20",
    amount: 1000,
    description: "Brake service",
  },
  {
    id: 1005,
    vehicle: "Nissan Altima",
    expenseDate: "2024-02-19",
    amount: 400,
    description: "Car wash",
  },
  {
    id: 1006,
    vehicle: "BMW X5",
    expenseDate: "2024-02-18",
    amount: 1200,
    description: "Wheel alignment",
  },
  {
    id: 1007,
    vehicle: "Audi A4",
    expenseDate: "2024-02-17",
    amount: 600,
    description: "Engine tune-up",
  },
  {
    id: 1008,
    vehicle: "Tesla Model 3",
    expenseDate: "2024-02-16",
    amount: 1500,
    description: "Electrical repair",
  },
  {
    id: 1009,
    vehicle: "Mercedes-Benz E-Class",
    expenseDate: "2024-02-15",
    amount: 900,
    description: "Air conditioning service",
  },
  {
    id: 1010,
    vehicle: "Lexus RX",
    expenseDate: "2024-02-14",
    amount: 700,
    description: "Detailing",
  },
  {
    id: 1011,
    vehicle: "Volkswagen Golf",
    expenseDate: "2024-02-13",
    amount: 200,
    description: "Fluid top-up",
  },
  {
    id: 1012,
    vehicle: "Subaru Outback",
    expenseDate: "2024-02-12",
    amount: 100,
    description: "Windshield replacement",
  },
];
export const TechnicianTaskData = [
  {
    id: 1001,
    taskName: "Oil Change",
    taskCategory: "Maintenance",
    technicianName: "John Doe",
    serviceLocation: "Auto Shop A",
    reportingTime: "2024-02-23 8:00 AM",
  },
  {
    id: 1002,
    taskName: "Tire Rotation",
    taskCategory: "Maintenance",
    technicianName: "Alice Smith",
    serviceLocation: "Auto Shop B",
    reportingTime: "2024-02-22 9:30 AM",
  },
  {
    id: 1003,
    taskName: "Brake Inspection",
    taskCategory: "Maintenance",
    technicianName: "Michael Johnson",
    serviceLocation: "Auto Shop C",
    reportingTime: "2024-02-21 10:15 AM",
  },
  {
    id: 1004,
    taskName: "Car Wash",
    taskCategory: "Cleaning",
    technicianName: "Emily Brown",
    serviceLocation: "Auto Spa X",
    reportingTime: "2024-02-20 11:45 AM",
  },
  {
    id: 1005,
    taskName: "Wheel Alignment",
    taskCategory: "Repair",
    technicianName: "David Wilson",
    serviceLocation: "Auto Shop Y",
    reportingTime: "2024-02-19 1:20 PM",
  },
  {
    id: 1006,
    taskName: "Headlight Replacement",
    taskCategory: "Repair",
    technicianName: "Jessica Martinez",
    serviceLocation: "Auto Shop Z",
    reportingTime: "2024-02-18 2:10 PM",
  },
  {
    id: 1007,
    taskName: "Engine Diagnostic",
    taskCategory: "Repair",
    technicianName: "Chris Lee",
    serviceLocation: "Garage A",
    reportingTime: "2024-02-17 4:00 PM",
  },
  {
    id: 1008,
    taskName: "Fluid Top-Up",
    taskCategory: "Maintenance",
    technicianName: "Sophia Taylor",
    serviceLocation: "Auto Shop D",
    reportingTime: "2024-02-16 8:30 AM",
  },
  {
    id: 1009,
    taskName: "Battery Check",
    taskCategory: "Maintenance",
    technicianName: "Daniel Anderson",
    serviceLocation: "Auto Shop E",
    reportingTime: "2024-02-15 9:00 AM",
  },
  {
    id: 1010,
    taskName: "Interior Detailing",
    taskCategory: "Cleaning",
    technicianName: "Olivia Garcia",
    serviceLocation: "Auto Spa B",
    reportingTime: "2024-02-14 11:20 AM",
  },
  {
    id: 1011,
    taskName: "AC System Inspection",
    taskCategory: "Repair",
    technicianName: "James Hernandez",
    serviceLocation: "Auto Shop F",
    reportingTime: "2024-02-13 1:45 PM",
  },
  {
    id: 1012,
    taskName: "Radiator Flush",
    taskCategory: "Maintenance",
    technicianName: "Emma Rodriguez",
    serviceLocation: "Auto Shop G",
    reportingTime: "2024-02-12 3:30 PM",
  },
];
export const AlertData = [
  {
    id: 1001,
    name: "Alert 1",
    alertType: "911",
    createdDate: "2024-02-23",
    notification: "Emergency",
    reason: "Medical emergency",
    timezone: "GMT-5:00",
    parentCompany: "Company1",
    parentBusiness: "Business Group1",
  },
  {
    id: 1002,
    name: "Alert 2",
    alertType: "Crash Detection",
    createdDate: "2024-02-22",
    notification: "Critical",
    reason: "Vehicle collision",
    timezone: "GMT-8:00",
    parentCompany: "Company1",
    parentBusiness: "Business Group1",
  },
  {
    id: 1003,
    name: "Alert 3",
    alertType: "Fire Alarm",
    createdDate: "2024-02-21",
    notification: "Emergency",
    reason: "Fire detected",
    timezone: "GMT-7:00",
    parentCompany: "Company1",
  },
  {
    id: 1004,
    name: "Alert 4",
    alertType: "Security Breach",
    createdDate: "2024-02-20",
    notification: "Critical",
    reason: "Unauthorized access",
    timezone: "GMT-4:00",
    parentCompany: "Company2",
  },
  {
    id: 1005,
    name: "Alert 5",
    alertType: "Flood Warning",
    createdDate: "2024-02-19",
    notification: "Emergency",
    reason: "Heavy rainfall",
    timezone: "GMT+2:00",
    parentCompany: "Company2",
    parentBusiness: "Business Group2",
  },
  {
    id: 1006,
    name: "Alert 6",
    alertType: "Power Outage",
    createdDate: "2024-02-18",
    notification: "Urgent",
    reason: "Electrical failure",
    timezone: "GMT+1:00",
    parentCompany: "Company2",
    parentBusiness: "Business Group3",
  },
  {
    id: 1007,
    name: "Alert 7",
    alertType: "Earthquake",
    createdDate: "2024-02-17",
    notification: "Emergency",
    reason: "Seismic activity detected",
    timezone: "GMT-6:00",
    parentCompany: "Company3",
    parentBusiness: "Business Group3",
  },
  {
    id: 1008,
    name: "Alert 8",
    alertType: "Tornado Warning",
    createdDate: "2024-02-16",
    notification: "Urgent",
    reason: "Severe weather",
    timezone: "GMT-5:00",
    parentCompany: "Company3",
    parentBusiness: "Business Group2",
  },
  {
    id: 1009,
    name: "Alert 9",
    alertType: "Gas Leak",
    createdDate: "2024-02-15",
    notification: "Critical",
    reason: "Gas detected",
    timezone: "GMT-7:00",
    parentCompany: "Company3",
    parentBusiness: "Business Group2",
  },
  {
    id: 1010,
    name: "Alert 10",
    alertType: "Suspicious Activity",
    createdDate: "2024-02-14",
    notification: "Emergency",
    reason: "Security breach detected",
    timezone: "GMT-8:00",
    parentCompany: "Company4",
    parentBusiness: "Business Group3",
  },
  {
    id: 1011,
    name: "Alert 11",
    alertType: "Severe Weather",
    createdDate: "2024-02-13",
    notification: "Urgent",
    reason: "Extreme weather conditions",
    timezone: "GMT+3:00",
    parentCompany: "Company4",
    parentBusiness: "Business Group3",
  },
  {
    id: 1012,
    name: "Alert 12",
    alertType: "Traffic Congestion",
    createdDate: "2024-02-12",
    notification: "Routine",
    reason: "Heavy traffic",
    timezone: "GMT-4:00",
    parentCompany: "Company4",
    parentBusiness: "Business Group4",
  },
];
export const ClassifyTripData = [
  {
    status: "active",
    tripId: 1001,
    startTime: "2-23-2024 8:00:00 AM",
    startLocation: "City A",
    reachTime: "2-23-2024 10:00:00 AM",
    reachLocation: "City B",
    distance: 150,
    fuelConsumption: 10,
    driver: "John Doe",
    branch: "Branch1",
  },
  {
    status: "active",
    tripId: 1002,
    startTime: "2-22-2024 9:00:00 AM",
    startLocation: "City B",
    reachTime: "2-22-2024 11:30:00 AM",
    reachLocation: "City C",
    distance: 200,
    fuelConsumption: 15,
    driver: "Jane Smith",
    branch: "Branch1",
  },
  {
    status: "active",
    tripId: 1003,
    startTime: "2-21-2024 11:30:00 AM",
    startLocation: "City C",
    reachTime: "2-21-2024 2:00:00 PM",
    reachLocation: "City D",
    distance: 180,
    fuelConsumption: 12,
    driver: "Mike Johnson",
    branch: "Branch1",
  },
  {
    status: "completed",
    tripId: 1004,
    startTime: "2-20-2024 10:00:00 AM",
    startLocation: "City D",
    reachTime: "2-20-2024 12:30:00 PM",
    reachLocation: "City E",
    distance: 220,
    fuelConsumption: 18,
    driver: "Emily Wilson",
    branch: "Branch2",
  },
  {
    status: "completed",
    tripId: 1005,
    startTime: "2-19-2024 8:30:00 AM",
    startLocation: "City E",
    reachTime: "2-19-2024 11:00:00 AM",
    reachLocation: "City F",
    distance: 190,
    fuelConsumption: 14,
    driver: "David Brown",
    branch: "Branch2",
  },
  {
    status: "completed",
    tripId: 1006,
    startTime: "2-18-2024 7:45:00 AM",
    startLocation: "City F",
    reachTime: "2-18-2024 10:15:00 AM",
    reachLocation: "City G",
    distance: 210,
    fuelConsumption: 16,
    driver: "Sarah Garcia",
    branch: "Branch2",
  },
  {
    status: "planned",
    tripId: 1007,
    startTime: "2-17-2024 9:15:00 AM",
    startLocation: "City G",
    reachTime: "2-17-2024 11:45:00 AM",
    reachLocation: "City H",
    distance: 180,
    fuelConsumption: 12,
    driver: "Michael Martinez",
    branch: "branch3",
  },
  {
    status: "planned",
    tripId: 1008,
    startTime: "2-16-2024 10:30:00 AM",
    startLocation: "City H",
    reachTime: "2-16-2024 1:00:00 PM",
    reachLocation: "City I",
    distance: 240,
    fuelConsumption: 20,
    driver: "Jessica Taylor",
    branch: "Branch3",
  },
  {
    status: "planned",
    tripId: 1009,
    startTime: "2-15-2024 8:45:00 AM",
    startLocation: "City I",
    reachTime: "2-15-2024 11:15:00 AM",
    reachLocation: "City J",
    distance: 200,
    fuelConsumption: 15,
    driver: "Daniel Anderson",
    branch: "Branch3",
  },
  {
    status: "active",
    tripId: 1010,
    startTime: "2-14-2024 11:00:00 AM",
    startLocation: "City J",
    reachTime: "2-14-2024 1:30:00 PM",
    reachLocation: "City K",
    distance: 180,
    fuelConsumption: 12,
    driver: "Olivia Thomas",
    branch: "Branch3",
  },
  {
    status: "active",
    tripId: 1011,
    startTime: "2-13-2024 7:30:00 AM",
    startLocation: "City K",
    reachTime: "2-13-2024 10:00:00 AM",
    reachLocation: "City L",
    distance: 220,
    fuelConsumption: 18,
    driver: "William Rodriguez",
    branch: "Branch3",
  },
  {
    status: "planned",
    tripId: 1012,
    startTime: "2-12-2024 9:45:00 AM",
    startLocation: "City L",
    reachTime: "2-12-2024 12:15:00 PM",
    reachLocation: "City M",
    distance: 210,
    fuelConsumption: 16,
    driver: "Emma Wilson",
    branch: "Branch4",
  },
];
export const GeofenceData = [
  {
    id: 1001,
    geofenceName: "Office",
    geofenceType: "Restricted",
    contactNo: "+1234567890",
    address: "123 Main Street, City A",
    description: "Restricted area for employees only",
    geofenceAccess: "Allowed",
    parentCompany: "Company1",
    parentBusiness: "Business Group3",
    createdDate: "2024-02-23",
  },
  {
    id: 1002,
    geofenceName: "Home",
    geofenceType: "Safe",
    contactNo: "+1987654321",
    address: "456 Elm Street, City B",
    description: "Safe zone for family members",
    geofenceAccess: "Allowed",
    parentCompany: "Company2",
    parentBusiness: "Business Group3",

    createdDate: "2024-02-21",
  },
  {
    id: 1003,
    geofenceName: "School",
    geofenceType: "Restricted",
    contactNo: "+1122334455",
    address: "789 Oak Street, City C",
    description: "Restricted area for students and staff",
    geofenceAccess: "Allowed",
    parentBusiness: "Business Group3",
    parentCompany: "Company2",
    createdDate: "2024-02-22",
  },
  {
    id: 1004,
    geofenceName: "Park",
    geofenceType: "Public",
    contactNo: "+1555666777",
    address: "101 Maple Avenue, City D",
    description: "Public park for recreational activities",
    geofenceAccess: "Allowed",
    parentCompany: "Company3",
    parentBusiness: "Business Group3",

    createdDate: "2024-01-23",
  },
  {
    id: 1005,
    geofenceName: "Mall",
    geofenceType: "Commercial",
    contactNo: "+1444333222",
    address: "202 Pine Street, City E",
    description: "Shopping mall for customers",
    geofenceAccess: "Allowed",
    parentCompany: "Company3",
    parentBusiness: "Business Group1",

    createdDate: "2024-02-17",
  },
  {
    id: 1006,
    geofenceName: "Hospital",
    geofenceType: "Restricted",
    contactNo: "+1999888777",
    address: "303 Cedar Street, City F",
    description: "Restricted area for medical personnel",
    geofenceAccess: "Allowed",
    parentBusiness: "Business Group1",

    parentCompany: "Company3",
    createdDate: "2024-02-10",
  },
  {
    id: 1007,
    geofenceName: "Airport",
    geofenceType: "Restricted",
    contactNo: "+1888777666",
    address: "404 Birch Street, City G",
    description: "Restricted area for airport staff",
    geofenceAccess: "Allowed",
    parentBusiness: "Business Group1",

    parentCompany: "Company3",
    createdDate: "2024-01-10",
  },
  {
    id: 1008,
    geofenceName: "Gym",
    geofenceType: "Restricted",
    contactNo: "+1666555444",
    address: "505 Cedar Street, City H",
    description: "Restricted area for gym members",
    geofenceAccess: "Allowed",
    parentCompany: "Company4",
    parentBusiness: "Business Group1",

    createdDate: "2024-02-12",
  },
  {
    id: 1009,
    geofenceName: "Restaurant",
    geofenceType: "Commercial",
    contactNo: "+1777444333",
    address: "606 Maple Avenue, City I",
    description: "Restaurant for dining",
    geofenceAccess: "Allowed",
    parentBusiness: "Business Group1",
    parentCompany: "Company4",
    createdDate: "2024-01-13",
  },
  {
    id: 1010,
    geofenceName: "Construction Site",
    geofenceType: "Restricted",
    contactNo: "+1333222111",
    address: "707 Elm Street, City J",
    description: "Restricted area for construction workers",
    geofenceAccess: "Allowed",
    parentCompany: "Company4",
    parentBusiness: "Business Group1",

    createdDate: "2024-02-10",
  },
  {
    id: 1011,
    geofenceName: "Library",
    geofenceType: "Public",
    contactNo: "+1222111333",
    address: "808 Oak Street, City K",
    description: "Public library for reading",
    geofenceAccess: "Allowed",
    parentBusiness: "Business Group1",

    parentCompany: "Company4",
    createdDate: "2024-01-13",
  },
  {
    id: 1012,
    geofenceName: "Warehouse",
    geofenceType: "Restricted",
    contactNo: "+1000000000",
    address: "909 Pine Street, City L",
    description: "Restricted area for warehouse employees",
    geofenceAccess: "Allowed",
    parentBusiness: "Business Group2",

    parentCompany: "Company4",
    createdDate: "2024-02-20",
  },
];

export const BillingData = [
  {
    id: "1001",
    createdDate: "2024-02-23",
    parentCompany: "Company4",
    parentBusiness: "Business Group1",
    userName: "John Doe",
    mobileNumber: "1234567890",
    email: "john.doe@example.com",
    billAmount: 500.0,
    paidAmount: 450.0,
  },
  {
    id: "1002",
    createdDate: "2024-02-21",
    parentCompany: "Company4",
    parentBusiness: "Business Group2",
    userName: "Alice Smith",
    mobileNumber: "9876543210",
    email: "alice.smith@example.com",
    billAmount: 750.0,
    paidAmount: 750.0,
  },
  {
    id: "2001",
    createdDate: "2024-03-10",
    parentCompany: "Company3",
    parentBusiness: "Business Group3",
    userName: "Bob Johnson",
    mobileNumber: "5555555555",
    email: "bob.johnson@example.com",
    billAmount: 300.0,
    paidAmount: 280.0,
  },
  {
    id: "2002",
    createdDate: "2024-01-24",
    parentCompany: "Company3",
    parentBusiness: "Business Group4",
    userName: "Emma Brown",
    mobileNumber: "1111111111",
    email: "emma.brown@example.com",
    billAmount: 1000.0,
    paidAmount: 1000.0,
  },
  {
    id: "3001",
    createdDate: "2024-02-11",
    parentCompany: "Company2",
    parentBusiness: "Business Group5",
    userName: "David Lee",
    mobileNumber: "9999999999",
    email: "david.lee@example.com",
    billAmount: 200.0,
    paidAmount: 200.0,
  },
  {
    id: "3002",
    createdDate: "2024-02-15",
    parentCompany: "Company2",
    parentBusiness: "Business Group1",
    userName: "Sarah Green",
    mobileNumber: "2222222222",
    email: "sarah.green@example.com",
    billAmount: 1200.0,
    paidAmount: 1150.0,
  },
  {
    id: "4001",
    createdDate: "2024-02-21",
    parentCompany: "Company2",
    parentBusiness: "Business Group1",
    userName: "Michael Wilson",
    mobileNumber: "3333333333",
    email: "michael.wilson@example.com",
    billAmount: 800.0,
    paidAmount: 750.0,
  },
  {
    id: "4002",
    createdDate: "2024-02-11",
    parentCompany: "Company1",
    parentBusiness: "Business Group2",
    userName: "Olivia Taylor",
    mobileNumber: "4444444444",
    email: "olivia.taylor@example.com",
    billAmount: 600.0,
    paidAmount: 600.0,
  },
  {
    id: "5001",
    createdDate: "2024-03-12",
    parentCompany: "Company1",
    parentBusiness: "Business Group3",
    userName: "James Johnson",
    mobileNumber: "7777777777",
    email: "james.johnson@example.com",
    billAmount: 400.0,
    paidAmount: 350.0,
  },
  {
    id: "5002",
    createdDate: "2024-02-11",
    parentCompany: "Company1",
    parentBusiness: "Business Group3",
    userName: "Sophia Davis",
    mobileNumber: "6666666666",
    email: "sophia.davis@example.com",
    billAmount: 900.0,
    paidAmount: 800.0,
  },
];
